### ISSUE TITLE
Проектът не се компилира

### ISSUE THREAD

**Issue by vgvassilev** [governmentbg/AISKAO#4]
Има липсващи зависимости като NLog

```
    <Reference Include="NLog">
      <HintPath>..\Eservices.AIS.Solution\packages\NLog.2.1.0\lib\net45\NLog.dll</HintPath>
    </Reference>
```

А ги търси в несъществуващата папка Eservices.AIS.Solution.

**Comment by TechnoLogica** [comment]
Това са nuget пакети, инсталирани от nuget package manager. За да се компилира, тези пакети трябва да се инсталират локално при вас. Трябва така да се каже да "възстановите пакетите" преди компилацията, при което nuget ще ги инсталира локално и след това компилатора ще намери съответните асемблита (dll файлове). В зависимост от версията на споменатия PM и IDE-то може да пробвате да разрешите Package restore по този https://docs.nuget.org/consume/package-restore/msbuild-integrated или този https://docs.nuget.org/consume/package-restore начин.

**Comment by vgvassilev** [comment]
Мда, това беше един от проблемите, другия е например, че липсва неймспейса WolfeReiter от WRAVLib, може да видите грешките на: https://ci.appveyor.com/project/vgvassilev/aiskao/build/2.1.23

**Comment by mitio** [comment]
@TechnoLogica това звучи като важен проблем. Поне двама човека докладват, че не могат да го компилират.

Можем ли да оправим проблемите и да обновим инструкциите за компилация в README-то?
